import { Bot, CircleGauge, Cpu, SlidersHorizontal, Wrench, Zap } from 'lucide-react'

export const skillHubModules = [
  {
    id: 'plc-control',
    sectionId: 'skill-plc-control',
    title: 'PLC Control',
    shortLabel: 'PLC',
    equipment: 'plc',
    icon: Cpu,
    position: [-2.65, 0.18, -0.85],
    labelPosition: [-0.08, 2.32, 0.5],
    accent: '#9bea63',
    description: 'Hands-on PLC training focused on industrial inputs, outputs, logic, and troubleshooting.',
    bullets: [
      'Studio 5000 / Logix 5000 exposure',
      'Ladder Logic programming',
      'SFC sequence logic',
      'PLC tags, inputs, outputs, and basic program structure',
      'I/O troubleshooting with sensors and actuators',
      'Understanding of how PLCs control motors, valves, cylinders, and automation devices',
      'Experience connecting PLC logic to real machine behavior',
    ],
    related: ['Studio 5000', 'Logix 5000', 'Ladder Logic', 'SFC', 'I/O', 'Tags', 'Sensors', 'Actuators'],
  },
  {
    id: 'instrumentation',
    sectionId: 'skill-instrumentation',
    title: 'Instrumentation',
    shortLabel: 'Instruments',
    equipment: 'instrumentation',
    icon: SlidersHorizontal,
    position: [0, 0.2, -1.5],
    labelPosition: [0.25, 2.72, 0.48],
    accent: '#8fb9aa',
    description: 'Process instrumentation training using equipment that measures real industrial variables.',
    bullets: [
      'Worked with process training equipment measuring four variables: flow, level, pressure, and temperature',
      'Understanding of how instruments monitor process conditions',
      'Experience with sensors, signals, calibration concepts, and process control basics',
      'Understanding of how instrumentation connects to PLC inputs and control systems',
      'Familiarity with process variables used in manufacturing and industrial automation',
      'Experience using precision instruments in technical training',
    ],
    related: ['Flow', 'Level', 'Pressure', 'Temperature', 'Sensors', 'Process Monitoring', 'Calibration Concepts', 'Precision Instruments'],
  },
  {
    id: 'motor-controls',
    sectionId: 'skill-motor-controls',
    title: 'Motor Controls',
    shortLabel: 'Motors',
    equipment: 'motor',
    icon: Zap,
    position: [2.45, 0.18, -0.75],
    labelPosition: [0.1, 2.25, 0.48],
    accent: '#9bea63',
    description: 'Hands-on training with electrical control circuits and industrial motor control components.',
    bullets: [
      'Motor control circuits and industrial wiring concepts',
      'Relays, contactors, overloads, switches, and control devices',
      'Basic VFD understanding',
      'Reading electrical schematics',
      'Understanding control circuit logic',
      'Troubleshooting basic motor control issues safely and methodically',
    ],
    related: ['Motor Controls', 'VFDs', 'Contactors', 'Relays', 'Overloads', 'Schematics', 'Wiring'],
  },
  {
    id: 'fluid-power',
    sectionId: 'skill-fluid-power',
    title: 'Pneumatics / Hydraulics',
    shortLabel: 'Fluid Power',
    equipment: 'fluid',
    icon: CircleGauge,
    position: [2.15, 0.18, 1.35],
    labelPosition: [0.45, 1.72, 0.55],
    accent: '#8fb9aa',
    description: 'Training with fluid power systems used in automation and industrial equipment.',
    bullets: [
      'Pneumatic cylinders, solenoid valves, actuators, and air pressure requirements',
      'Hydraulic and pneumatic trainer experience',
      'Understanding of fluid power components and safety',
      'Testing devices to confirm proper operation',
      'Understanding how pneumatic and hydraulic systems connect to PLC-controlled machines',
      'Basic troubleshooting of cylinders, valves, pressure, and movement issues',
    ],
    related: ['Pneumatics', 'Hydraulics', 'Solenoids', 'Cylinders', 'Actuators', 'Air Pressure', 'Fluid Power'],
  },
  {
    id: 'robotics-automation',
    sectionId: 'skill-robotics-automation',
    title: 'Robotics / Automation',
    shortLabel: 'Robotics',
    equipment: 'robot',
    icon: Bot,
    position: [-1.45, 0.18, 1.2],
    labelPosition: [-0.5, 2.68, 0.42],
    accent: '#9bea63',
    description: 'Automation and robotics training connected to industrial motion and sequencing.',
    bullets: [
      'Robotics coursework and lab experience',
      'FANUC robot exposure through supervised training',
      'Understanding of automated sequences and machine operation',
      'Sensors, actuators, and control flow',
      'Basic path, motion, and programming concepts from lab training',
      'Understanding how robots fit into automated manufacturing systems',
    ],
    related: ['Robotics', 'Automation', 'FANUC', 'Sensors', 'Actuators', 'Sequences', 'Industrial Systems'],
  },
  {
    id: 'industrial-mechanics',
    sectionId: 'skill-industrial-mechanics',
    title: 'Industrial Mechanics',
    shortLabel: 'Mechanics',
    equipment: 'mechanics',
    icon: Wrench,
    position: [0.25, 0.2, 2.05],
    labelPosition: [0.1, 1.92, 0.52],
    accent: '#8fb9aa',
    description: 'Hands-on industrial mechanics foundation using maintenance tools, schematics, measurement equipment, and systematic troubleshooting.',
    bullets: [
      'Multimeters and precision instruments',
      'Electrical checks and wiring verification',
      'Reading schematics and technical diagrams',
      'Mechanical alignment and basic maintenance tasks',
      'Troubleshooting sensors, actuators, motors, and control circuits',
      'Industrial equipment troubleshooting',
      'Safe, step-by-step diagnostic approach for industrial equipment',
    ],
    related: ['Industrial Mechanics', 'Multimeter', 'Precision Instruments', 'Schematics', 'Wiring Checks', 'Troubleshooting', 'Maintenance'],
  },
]
